#!/usr/bin/env bash
# Productionized Keepalived Entrypoint
set -e

# Support graceful shutdown
child_pid=0
function cleanup() {
  echo "Graceful shutdown requested..."
  if [ $child_pid -ne 0 ]; then
    kill -TERM "$child_pid"
    wait "$child_pid"
  fi
  echo "Shutdown complete."
  exit 0
}
trap 'cleanup' SIGTERM

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
# Standard volume mount: /config/keepalived.conf and /config/scripts/
CONFIG_DIR="/config"
SCRIPTS_SRC="${CONFIG_DIR}/scripts"
SCRIPTS_DEST="/etc/keepalived/scripts"

# Internal runtime config path
CONF_FILE="/etc/keepalived/keepalived.conf"
FORCE_REGENERATE=${FORCE_REGENERATE:-false}

# ---------------------------------------------------------------------------
# Resolve interface
# ---------------------------------------------------------------------------
INTERFACE=${INTERFACE:-$HOST_INTERFACE}
INTERFACE=${INTERFACE:-eth0}
export INTERFACE

# ---------------------------------------------------------------------------
# Build VIP_ADDRESSES from VIP_n_IP variables if not set directly
# ---------------------------------------------------------------------------
if [ -z "$VIP_ADDRESSES" ]; then
    # shellcheck disable=SC2207
    VIPS=($(env | grep -E "^VIP_[0-9]+_IP=" | sort -t_ -k2 -n | cut -d= -f2))
    if [ ${#VIPS[@]} -gt 0 ]; then
        VIP_ADDRESSES="${VIPS[*]}"
        export VIP_ADDRESSES
        echo "Built VIP_ADDRESSES: $VIP_ADDRESSES"
    fi
fi

# ---------------------------------------------------------------------------
# Helper: generate keepalived.conf from environment variables
# Writes to $1 (destination file path)
# ---------------------------------------------------------------------------
generate_conf() {
    local dest="$1"
    mkdir -p "$(dirname "$dest")"
    # Truncate first, then append remaining blocks so repeated calls don't stack
    : > "$dest"
    printf '%s\n' '# Generated by run-keepalived.sh (see docker README.md)' \
      '' \
      '# vrrp_script check_service {' \
      '#     script "/etc/keepalived/scripts/check_service.sh"' \
      '#     interval 3' \
      '#     weight -20 # Reduce priority by 20 if script fails' \
      '#     fall 3' \
      '#     rise 2' \
      '# }' \
      '# ' \
      '# vrrp_instance VI_999 {' \
      '#     state BACKUP # Always start in BACKUP and let priority decide' \
      '#     interface eth' \
      '#     virtual_router_id 99' \
      '#     priority 50 # Higher base priority' \
      '#     advert_int 1' \
      '#     authentication {' \
      '#         auth_type PASS' \
      '#         auth_pass pass1234' \
      '#     }' \
      '#     virtual_ipaddress {' \
      '#         192.168.0.253/22 dev ens3' \
      '#     }' \
      '#     track_script {' \
      '#         check_service' \
      '#     }' \
      '#     notify /etc/keepalived/scripts/notify.sh' \
      '# }' \
      '' \
      'global_defs {' \
      '  enable_script_security' \
      '  script_user root   # or another appropriate user' \
      '}' '' >> "$dest"


    if [ -z "$INSTANCES" ]; then
        # No INSTANCES defined — write a documented placeholder
        cat >> "$dest" <<'PLACEHOLDER'
#
# No INSTANCES environment variable was set.
#
# To generate a config automatically, set INSTANCES and per-instance variables:
#
#   INSTANCES=VIP_1,VIP_2
#   VIP_1_ID=51
#   VIP_1_STATE=MASTER
#   VIP_1_PRIORITY=100
#   VIP_1_VIP=192.168.1.100/24
#   VIP_1_PASS=8ChrPwd1
#
# Or edit this file directly with your own vrrp_instance blocks.

PLACEHOLDER
        return 0
    fi

    IFS=',' read -ra ADDR <<< "$INSTANCES"
    for instance in "${ADDR[@]}"; do
        instance=$(echo "$instance" | xargs)

        ID_VAR="${instance}_ID"
        PRIO_VAR="${instance}_PRIORITY"
        VIP_VAR="${instance}_VIP"
        PASS_VAR="${instance}_PASS"
        STATE_VAR="${instance}_STATE"
        INT_VAR="${instance}_INTERFACE"

        ID=${!ID_VAR}
        PRIO=${!PRIO_VAR}
        VIP=${!VIP_VAR}
        VIP=${VIP:-$VIP_ADDRESSES}
        PASS=${!PASS_VAR}
        STATE=${!STATE_VAR:-BACKUP}
        INT=${!INT_VAR:-$INTERFACE}

        if [ -z "$ID" ] || [ -z "$PRIO" ] || [ -z "$VIP" ] || [ -z "$PASS" ]; then
            echo "Error: Missing configuration for instance $instance"
            echo "Ensure the following environment variables are set:"
            echo "  ${instance}_ID, ${instance}_PRIORITY, ${instance}_VIP, ${instance}_PASS"
            exit 1
        fi

        cat >> "$dest" <<EOF

vrrp_instance $instance {
    state $STATE
    interface $INT
    virtual_router_id $ID
    priority $PRIO
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass $PASS
    }
    virtual_ipaddress {
EOF
        for v in $VIP; do
            echo "        $v dev $INT" >> "$dest"
        done

        cat >> "$dest" <<EOF
    }
}
EOF
    done
}

# ---------------------------------------------------------------------------
# init command — scaffold /config and exit (keepalived is NOT started)
# ---------------------------------------------------------------------------
if [ "$1" == "init" ]; then
    echo "=== Keepalived Init Mode ==="
    echo "Scaffolding config directory at ${CONFIG_DIR} ..."

    if [ ! -w "$CONFIG_DIR" ]; then
        echo "Error: ${CONFIG_DIR} is not writable. Mount a writable volume at /config."
        exit 1
    fi

    # Generate keepalived.conf template
    if [ -f "${CONFIG_DIR}/keepalived.conf" ]; then
        echo "Warning: ${CONFIG_DIR}/keepalived.conf already exists — skipping (use FORCE_REGENERATE=true to overwrite)."
    fi

    if [ ! -f "${CONFIG_DIR}/keepalived.conf" ] || [ "${FORCE_REGENERATE}" == "true" ]; then
        echo "Generating ${CONFIG_DIR}/keepalived.conf ..."
        generate_conf "${CONFIG_DIR}/keepalived.conf"
        echo "  -> ${CONFIG_DIR}/keepalived.conf written."
    fi

    # Create scripts directory and copy sample scripts
    mkdir -p "${CONFIG_DIR}/scripts"
    for sample in /app/scripts/*.sh; do
        dest="${CONFIG_DIR}/scripts/$(basename "$sample")"
        if [ -f "$dest" ]; then
            echo "  -> $(basename "$dest") already exists — skipping."
        else
            cp "$sample" "$dest"
            chmod +x "$dest"
            echo "  -> $(basename "$dest") copied."
        fi
    done

    echo ""
    echo "=== Init complete ==="
    echo ""
    echo "Next steps:"
    echo "  1. Edit ${CONFIG_DIR}/keepalived.conf with your VRRP configuration."
    echo "  2. Optionally customize scripts in ${CONFIG_DIR}/scripts/."
    echo "  3. Start the container normally (without 'init') using the same volume mount."
    echo ""
    echo "Example docker-compose.yml snippet:"
    echo "  volumes:"
    echo "    - ./keepalived-config:/config:ro"
    echo ""
    exit 0
fi

# ---------------------------------------------------------------------------
# Check if "regenerate" was passed as the first argument
# ---------------------------------------------------------------------------
if [ "$1" == "regenerate" ]; then
    FORCE_REGENERATE=true
    shift
fi

# ---------------------------------------------------------------------------
# Prepare scripts in /etc/keepalived/scripts/
#   1. Bundled image scripts from /app/scripts/ (base)
#   2. User-provided scripts from /config/scripts/ (overlay, if present)
# After copying, all scripts are owned root:root and chmod 755.
# ---------------------------------------------------------------------------
mkdir -p "$SCRIPTS_DEST"

if [ -d "/app/scripts" ] && [ "$(ls -A /app/scripts 2>/dev/null)" ]; then
    echo "Copying bundled scripts: $(ls /app/scripts)"
    cp /app/scripts/* "$SCRIPTS_DEST"/
else
    echo "Warning: no bundled scripts found in /app/scripts"
fi

if [ -d "$SCRIPTS_SRC" ] && [ "$(ls -A "$SCRIPTS_SRC" 2>/dev/null)" ]; then
    echo "Loading user scripts from ${SCRIPTS_SRC} -> ${SCRIPTS_DEST} ..."
    cp "${SCRIPTS_SRC}"/* "$SCRIPTS_DEST"/
fi

# Use find so chown/chmod are safe on an empty directory (no glob expansion issues)
find "$SCRIPTS_DEST" -type f -exec chown root:root {} \;
find "$SCRIPTS_DEST" -type f -exec chmod 755 {} \;
echo "Scripts prepared in ${SCRIPTS_DEST}: $(ls "${SCRIPTS_DEST}" 2>/dev/null || echo 'none')"

# ---------------------------------------------------------------------------
# Config resolution:
#   1. /config/keepalived.conf  (volume mount — highest priority)
#   2. /mnt/keepalived.conf     (legacy override path)
#   3. Generate from env vars
# ---------------------------------------------------------------------------
if [ -s "${CONFIG_DIR}/keepalived.conf" ]; then
    echo "Found custom configuration at ${CONFIG_DIR}/keepalived.conf. Copying to ${CONF_FILE}."
    mkdir -p "$(dirname "$CONF_FILE")"
    cp "${CONFIG_DIR}/keepalived.conf" "$CONF_FILE"
elif [ -s "/mnt/keepalived.conf" ]; then
    echo "Found legacy configuration at /mnt/keepalived.conf. Copying to ${CONF_FILE}."
    mkdir -p "$(dirname "$CONF_FILE")"
    cp /mnt/keepalived.conf "$CONF_FILE"
elif [ -s "$CONF_FILE" ] && [ "$FORCE_REGENERATE" != "true" ]; then
    echo "Using existing configuration at ${CONF_FILE}."
else
    echo "Generating configuration from environment variables (Force: ${FORCE_REGENERATE})."
    generate_conf "$CONF_FILE"
fi

echo "--- keepalived.conf content ---"
sed -e 's/auth_pass .*/auth_pass #REDACTED#/g' "$CONF_FILE"
echo "---------------------------------"

# ---------------------------------------------------------------------------
# Start keepalived; use "$@" to pass any extra arguments (e.g. --log-detail)
# ---------------------------------------------------------------------------
/usr/sbin/keepalived -f "$CONF_FILE" --dont-fork --log-console --log-facility 7 "$@" &
child_pid=$!

echo "keepalived process started with PID: ${child_pid}"
wait "$child_pid"
