#!/usr/bin/env bash
# Productionized Keepalived Entrypoint
set -e

# Support graceful shutdown
child_pid=0
function cleanup() {
  echo "Graceful shutdown requested..."
  if [ $child_pid -ne 0 ]; then
    kill -TERM "$child_pid"
    wait "$child_pid"
  fi
  echo "Shutdown complete."
  exit 0
}
trap 'cleanup' SIGTERM

# Path to the configuration file
# We use /etc/keepalived/keepalived.conf as the standard path
CONF_FILE="/etc/keepalived/keepalived.conf"
FORCE_REGENERATE=${FORCE_REGENERATE:-false}

# Build VIP_ADDRESSES from individual VIP_1_IP, VIP_2_IP... if not provided
if [ -z "$VIP_ADDRESSES" ]; then
    echo "VIP_ADDRESSES not found. Building from VIP_n_IP variables..."
    # Get all environment variables starting with VIP_ and ending with _IP
    # Sort them by the number in the middle (VIP_1_IP, VIP_2_IP...)
    # shellcheck disable=SC2207
    VIPS=($(env | grep -E "^VIP_[0-9]+_IP=" | sort -t_ -k2 -n | cut -d= -f2))
    VIP_ADDRESSES="${VIPS[*]}"
    export VIP_ADDRESSES
    echo "Built VIP_ADDRESSES: $VIP_ADDRESSES"
fi
env | grep VIP
echo "VIP ADDRESSES $VIP_ADDRESSES"

# Use HOST_INTERFACE if INTERFACE is not explicitly set
INTERFACE=${INTERFACE:-$HOST_INTERFACE}
INTERFACE=${INTERFACE:-eth0}
export INTERFACE

# Check if "regenerate" was passed as the first argument
if [ "$1" == "regenerate" ]; then
    FORCE_REGENERATE=true
    shift # Remove "regenerate" from the arguments list
fi

# Logic for configuration:
# 1. If a custom config exists at /mnt/keepalived.conf, use it (highest priority override)
# 2. If CONF_FILE exists and not forcing regeneration, use it
# 3. Otherwise, generate from environment variables
if [ -s "/mnt/keepalived.conf" ]; then
    echo "Found custom configuration at /mnt/keepalived.conf. Copying to $CONF_FILE."
    cp /mnt/keepalived.conf "$CONF_FILE"
elif [ -s "$CONF_FILE" ] && [ "$FORCE_REGENERATE" != "true" ]; then
    echo "Using existing configuration at $CONF_FILE."
else
    echo "Generating configuration from environment variables (Force: $FORCE_REGENERATE)."
    
    mkdir -p /etc/keepalived
    echo "# Generated by run-keepalived.sh" > "$CONF_FILE"

    # Default interface if not specified per instance
    INTERFACE=${INTERFACE:-eth0}

    # Split INSTANCES by comma
    IFS=',' read -ra ADDR <<< "$INSTANCES"
    for instance in "${ADDR[@]}"; do
        # Clean whitespace
        instance=$(echo "$instance" | xargs)
        
        # Extract variables dynamically
        ID_VAR="${instance}_ID"
        PRIO_VAR="${instance}_PRIORITY"
        VIP_VAR="${instance}_VIP"
        PASS_VAR="${instance}_PASS"
        STATE_VAR="${instance}_STATE"
        INT_VAR="${instance}_INTERFACE"

        ID=${!ID_VAR}
        PRIO=${!PRIO_VAR}
        VIP=${!VIP_VAR}
        VIP=${VIP:-$VIP_ADDRESSES}
        PASS=${!PASS_VAR}
        STATE=${!STATE_VAR:-BACKUP}
        INT=${!INT_VAR:-$INTERFACE}

        if [ -z "$ID" ] || [ -z "$PRIO" ] || [ -z "$VIP" ] || [ -z "$PASS" ]; then
            echo "Error: Missing configuration for instance $instance"
            echo "Ensure the following environment variables are set:"
            echo " - ${instance}_ID"
            echo " - ${instance}_PRIORITY"
            echo " - ${instance}_VIP"
            echo " - ${instance}_PASS"
            exit 1
        fi

        cat >> "$CONF_FILE" <<EOF

vrrp_instance $instance {
    state $STATE
    interface $INT
    virtual_router_id $ID
    priority $PRIO
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass $PASS
    }
    virtual_ipaddress {
EOF
        # Add VIP addresses (supports space-separated list)
        for v in $VIP; do
            echo "        $v dev $INT" >> "$CONF_FILE"
        done

        cat >> "$CONF_FILE" <<EOF
    }
}
EOF
    done
fi

echo "--- keepalived.conf content ---"
cat "$CONF_FILE" | sed -e 's/auth_pass .*/auth_pass #REDACTED#/g'
echo "---------------------------------"

# Run keepalived in background to allow signal trapping
# Use "$@" to pass any additional arguments (like --log-detail)
/usr/sbin/keepalived -f "$CONF_FILE" --dont-fork --log-console --log-facility 7 "$@" &
child_pid=$!

echo "keepalived process started with PID: $child_pid"
wait "$child_pid"
